export enum UploadErrorsEnum {
	SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
	PATHNAME_MISSING = 'PATHNAME_MISSING',
	PATHNAME_INVALID = 'PATHNAME_INVALID',
	NO_FILES = 'NO_FILES',
	FILES_TOO_LARGE = 'FILES_TOO_LARGE',
	ALREADY_EXISTS = 'ALREADY_EXISTS',
	METADATA_MISMATCH = 'METADATA_MISMATCH',
	INVALID_METADATA = 'INVALID_METADATA',
	UNSUPPORTED_FILE_TYPE = 'UNSUPPORTED_FILE_TYPE'
}

export interface IUploadError {
	error: UploadErrorsEnum
	details?: string[]
}
